version: '3'

services:
  kafka-binance:
    build: .
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME}
      - APP_CODE=${APP_CODE}
      - APP_PORT=${APP_PORT}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MODE=${DB_MODE}
      - DB_MIGRATIONS=${DB_MIGRATIONS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_SSL=${KAFKA_SSL}
      - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - BINANCE_DEFAULT_ID
      - BINANCE_DEFAULT_KEY
      - BINANCE_DEFAULT_SECRET
    depends_on:
      - postgres
    links:
      - postgres:postgres

  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432/tcp

volumes:
  postgres_data:
    driver: local
