version: '3'

services:

  ################ REDIS ################

  redis:
    image: bitnami/redis
    restart: unless-stopped
    volumes:
      - redis_data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - ${REDIS_PORT}:6379/tcp

  redis-ui:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_UI_PORT}:8081/tcp
    depends_on:
      - redis

volumes:
  redis_data:
